version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - /var/www/proyecta-counter-server
    expose:
      - "3000"
    #environment:
    #  - RAILS_ENV=production
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "8080:80"
